name: pocketoptimizer
channels:
  - conda-forge
  - defaults
  - ostrokach
  - omnia
  - acellera
  - bioconda
  - oddt
  - psi4
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - acemd3=3.3.0=cuda100_0
  - alsa-lib=1.2.3.2=h166bdaf_0
  - ambertools=22.0=py39h904b211_1
  - anaconda-client=1.8.0=pyhd8ed1ab_0
  - anyio=3.6.1=py39hf3d152e_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py39hb9d737c_2
  - arpack=3.7.0=hdefa2d7_2
  - asttokens=2.0.5=pyhd8ed1ab_0
  - astunparse=1.6.3=pyhd8ed1ab_0
  - attr=2.5.1=h166bdaf_0
  - attrs=21.4.0=pyhd8ed1ab_0
  - babel=2.10.1=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.11.1=pyha770c72_0
  - bhmm=0.6.3=py39h16ac069_1004
  - biopython=1.79=py39h3811e60_1
  - bleach=5.0.0=pyhd8ed1ab_0
  - blosc=1.21.1=h83bc5f7_3
  - boost=1.74.0=py39h5472131_5
  - boost-cpp=1.74.0=h75c5d50_8
  - brotli=1.0.9=h166bdaf_7
  - brotli-bin=1.0.9=h166bdaf_7
  - brotlipy=0.7.0=py39hb9d737c_1004
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2022.5.18.1=ha878542_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.16.0=ha61ee94_1011
  - certifi=2022.5.18.1=py39hf3d152e_0
  - cffi=1.15.0=py39h4bc2ebd_0
  - charset-normalizer=2.0.12=pyhd8ed1ab_0
  - clyent=1.2.2=py_1
  - colorama=0.4.4=pyh9f0ad1d_0
  - cryptography=37.0.2=py39hd97740a_0
  - cudatoolkit=11.7.0=hd8887f6_10
  - curl=7.83.1=h7bff187_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - cython=0.29.30=py39h5a03fae_0
  - dbus=1.13.6=h5008d03_3
  - debugpy=1.6.0=py39h5a03fae_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - deeptime=0.4.2=py39h1832856_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - dill=0.3.5.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - et_xmlfile=1.0.1=py_1001
  - executing=0.8.3=pyhd8ed1ab_0
  - expat=2.4.8=h27087fc_0
  - ffevaluation=0.1.8=py39_0
  - fftw=3.3.10=nompi_h77c792f_102
  - flit-core=3.7.1=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.0=h8e229c2_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.33.3=py39hb9d737c_0
  - freetype=2.10.4=h0708190_1
  - gettext=0.19.8.1=h73d1719_1008
  - giflib=5.2.1=h36c2ea0_2
  - greenlet=1.1.2=py39h5a03fae_2
  - gst-plugins-base=1.20.2=hcf0ee16_0
  - gstreamer=1.20.2=hd4edc92_1
  - h5py=3.6.0=nompi_py39h7e08c79_100
  - hdf4=4.2.15=h10796ff_3
  - hdf5=1.12.1=nompi_h2386368_104
  - htmd=2.0.5=py39_0
  - htmd-deps=2.0.5=py39_0
  - icu=70.1=h27087fc_0
  - idna=3.3=pyhd8ed1ab_0
  - importlib-metadata=4.11.4=py39hf3d152e_0
  - importlib_metadata=4.11.4=hd8ed1ab_0
  - importlib_resources=5.7.1=pyhd8ed1ab_1
  - ipykernel=6.13.0=py39hef51801_0
  - ipython=8.4.0=py39hf3d152e_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.7.0=pyhd8ed1ab_0
  - jack=1.9.18=hfd4fe87_1001
  - jedi=0.18.1=py39hf3d152e_1
  - jinja2=3.1.2=pyhd8ed1ab_0
  - joblib=1.1.0=pyhd8ed1ab_0
  - jobqueues=0.8.0=py39_0
  - jpeg=9e=h166bdaf_1
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=4.6.0=pyhd8ed1ab_0
  - jupyter_client=7.3.1=pyhd8ed1ab_0
  - jupyter_console=6.4.3=pyhd8ed1ab_0
  - jupyter_core=4.10.0=py39hf3d152e_0
  - jupyter_server=1.17.0=pyhd8ed1ab_0
  - jupyterlab=3.4.2=pyhd8ed1ab_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_server=2.14.0=pyhd8ed1ab_0
  - jupyterlab_widgets=1.1.0=pyhd8ed1ab_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.2=py39hf939315_1
  - krb5=1.19.3=h3790be6_0
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=3.0=h9c3ff4c_0
  - libblas=3.9.0=14_linux64_openblas
  - libbrotlicommon=1.0.9=h166bdaf_7
  - libbrotlidec=1.0.9=h166bdaf_7
  - libbrotlienc=1.0.9=h166bdaf_7
  - libcap=2.64=ha37c62d_0
  - libcblas=3.9.0=14_linux64_openblas
  - libclang=14.0.4=default_h2e3cab8_0
  - libclang13=14.0.4=default_h3a83d3e_0
  - libcups=2.3.3=hf5a7f15_1
  - libcurl=7.83.1=h7bff187_0
  - libdb=6.2.32=h9c3ff4c_0
  - libdeflate=1.10=h7f98852_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=h9b69904_4
  - libffi=3.4.2=h7f98852_5
  - libflac=1.3.4=h27087fc_0
  - libgcc-ng=12.1.0=h8d9b700_16
  - libgfortran-ng=12.1.0=h69a702a_16
  - libgfortran5=12.1.0=hdcd56e2_16
  - libglib=2.70.2=h174f98d_4
  - libgomp=12.1.0=h8d9b700_16
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=14_linux64_openblas
  - libllvm11=11.1.0=hf817b99_3
  - libllvm14=14.0.4=he0ac6c6_0
  - libnetcdf=4.8.1=nompi_h329d8a1_102
  - libnghttp2=1.47.0=h727a467_0
  - libnsl=2.0.0=h7f98852_0
  - libogg=1.3.4=h7f98852_1
  - libopenblas=0.3.20=pthreads_h78a6416_0
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.37=h21135ba_2
  - libpq=14.3=hd77ab85_0
  - libsndfile=1.0.31=h9c3ff4c_1
  - libsodium=1.0.18=h36c2ea0_1
  - libssh2=1.10.0=ha56f1ee_2
  - libstdcxx-ng=12.1.0=ha89aaad_16
  - libtiff=4.4.0=h0fcbabc_0
  - libtool=2.4.6=h9c3ff4c_1008
  - libudev1=249=h166bdaf_2
  - libuuid=2.32.1=h7f98852_1000
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp=1.2.2=h3452ae3_0
  - libwebp-base=1.2.2=h7f98852_1
  - libxcb=1.13=h7f98852_1004
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.14=h22db469_0
  - libzip=1.8.0=h4de3113_1
  - libzlib=1.2.12=h166bdaf_0
  - llvmlite=0.38.1=py39h7d9a04d_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - lzo=2.10=h516909a_1000
  - markupsafe=2.1.1=py39hb9d737c_1
  - matplotlib=3.5.2=py39hf3d152e_0
  - matplotlib-base=3.5.2=py39h700656a_0
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mdtraj=1.9.7=py39h138c130_1
  - mistune=0.8.4=py39h3811e60_1005
  - mmcif_pdbx=2.0.0=pyh44b312d_0
  - mmtf-python=1.1.2=py_0
  - moleculekit=1.2.2=py39_0
  - msgpack-python=1.0.4=py39hf939315_0
  - msmtools=1.2.6=py39hce5d2b2_1
  - multiprocess=0.70.13=py39hb9d737c_1
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=8.0.29=haf5c9bc_1
  - mysql-libs=8.0.29=h28c427c_1
  - natsort=8.1.0=pyhd8ed1ab_0
  - nbclassic=0.3.7=pyhd8ed1ab_0
  - nbclient=0.6.4=pyhd8ed1ab_1
  - nbconvert=6.5.0=pyhd8ed1ab_0
  - nbconvert-core=6.5.0=pyhd8ed1ab_0
  - nbconvert-pandoc=6.5.0=pyhd8ed1ab_0
  - nbformat=5.4.0=pyhd8ed1ab_0
  - ncurses=6.3=h27087fc_1
  - nest-asyncio=1.5.5=pyhd8ed1ab_0
  - netcdf-fortran=4.5.4=nompi_h2b6e579_100
  - networkx=2.8.2=pyhd8ed1ab_0
  - nglview=3.0.3=pyh8a188c0_0
  - nomkl=1.0=h5ca1d4c_0
  - notebook=6.4.11=pyha770c72_0
  - notebook-shim=0.1.0=pyhd8ed1ab_0
  - nspr=4.32=h9c3ff4c_1
  - nss=3.78=h2350873_0
  - numba=0.55.1=py39h66db6d7_1
  - numexpr=2.8.0=py39h194a79d_102
  - numpy=1.21.6=py39h18676bf_0
  - ocl-icd=2.3.1=h7f98852_0
  - ocl-icd-system=1.0.0=1
  - openbabel=3.1.1=py39hee2736e_3
  - openjpeg=2.4.0=hb52868f_1
  - openmm=7.7.0=py39h15fbce5_1
  - openpyxl=3.0.9=pyhd8ed1ab_0
  - openssl=1.1.1o=h166bdaf_0
  - packaging=21.3=pyhd8ed1ab_0
  - packmol=20.010=h86c2bf4_0
  - pandas=1.4.2=py39h1832856_2
  - pandoc=2.18=ha770c72_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parmed=3.4.3=py39h5a03fae_2
  - parso=0.8.3=pyhd8ed1ab_0
  - pathos=0.2.9=pyhd8ed1ab_0
  - pcre=8.45=h9c3ff4c_0
  - pdb2pqr=3.4.1=pyhd8ed1ab_0
  - perl=5.32.1=2_h7f98852_perl5
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.1.1=py39hae2aec6_1
  - pint=0.19.2=pyhd8ed1ab_0
  - pip=22.1.2=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - plumed2=2.3.3+htmd.4=4
  - pox=0.3.1=pyhd8ed1ab_0
  - ppft=1.7.6.5=pyhd8ed1ab_0
  - prometheus_client=0.14.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.29=pyha770c72_0
  - prompt_toolkit=3.0.29=hd8ed1ab_0
  - propka=3.4.0=py39hef51801_3
  - protocolinterface=0.4.4=py_0
  - psfgen=1.6.9=0
  - psutil=5.9.1=py39hb9d737c_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pulseaudio=14.0=hbc9ff1d_7
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycairo=1.21.0=py39h0934665_1
  - pycparser=2.21=pyhd8ed1ab_0
  - pyemma=2.5.11=py39hde0f152_0
  - pygments=2.12.0=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyqt=5.15.4=py39h18e9c17_1
  - pyqt5-sip=12.9.0=py39h5a03fae_1
  - pyrsistent=0.18.1=py39hb9d737c_1
  - pysocks=1.7.1=py39hf3d152e_5
  - pytables=3.7.0=py39h2669a42_0
  - python=3.9.13=h9a8a25e_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.15.3=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytz=2022.1=pyhd8ed1ab_0
  - pyyaml=6.0=py39hb9d737c_4
  - pyzmq=23.1.0=py39headdf64_0
  - qt-main=5.15.3=hf97cb25_2
  - rdkit=2022.03.2=py39h89e00b9_1
  - readline=8.1=h46c0cb4_0
  - reportlab=3.5.68=py39he59360d_1
  - requests=2.27.1=pyhd8ed1ab_0
  - scikit-learn=1.1.1=py39h4037b75_0
  - scipy=1.8.1=py39he49c0e8_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=62.3.2=py39hf3d152e_0
  - sip=6.5.1=py39he80948d_2
  - six=1.16.0=pyh6c4a22f_0
  - smina=2020.12.10=h37f9cb6_0
  - snappy=1.1.9=hbd366e4_1
  - sniffio=1.2.0=py39hf3d152e_3
  - soupsieve=2.3.1=pyhd8ed1ab_0
  - sqlalchemy=1.4.37=py39hb9d737c_0
  - sqlite=3.38.5=h4ff8645_0
  - stack_data=0.2.0=pyhd8ed1ab_0
  - terminado=0.15.0=py39hf3d152e_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tinycss2=1.1.1=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tornado=6.1=py39hb9d737c_3
  - tqdm=4.64.0=pyhd8ed1ab_0
  - traitlets=5.2.2.post1=pyhd8ed1ab_0
  - tzdata=2022a=h191b570_0
  - unicodedata2=14.0.0=py39hb9d737c_1
  - urllib3=1.26.9=pyhd8ed1ab_0
  - vina=1.2.3=py39hc76a25d_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - weblogo=3.7.11=pyhd8ed1ab_0
  - websocket-client=1.3.2=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - widgetsnbextension=3.6.0=py39hf3d152e_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-libxt=1.2.1=h7f98852_2
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h7f98852_2
  - zeromq=4.3.4=h9c3ff4c_1
  - zipp=3.8.0=pyhd8ed1ab_0
  - zlib=1.2.12=h166bdaf_0
  - zstd=1.5.2=h8a70e8d_1
  - pip:
    - amberlite==22.0
    - amberutils==21.0
    - mmpbsa-py==16.0
    - packmol-memgen==1.2.3rc0
    - pdb4amber==22.0
    - pytraj==2.0.6
    - sander==22.0
